### PR TITLE
addition of transaction documentation and minor refactor to documentation

### PR DESCRIPTION
**Pull request by cogluca**
Hey, I thought that I should have been the one updating the docs for the transaction method, did a minor refactor to the table displaying the properties, and moved it up so that we can reference below all the future additions.

Let me know what you think about the change

### CODE REVIEW

**Comment by mateonunez** [comment]
Hey! 

The PR looks amazing I want to merge it as soon as possible. Can you rebase your branch with main?

**Comment by cogluca** [comment]
image

Looks like a single branch, not sure I understand what you mean by rebase

**Comment by mateonunez** [comment]
> image
> 
> Looks like a single branch, not sure I understand what you mean by rebase

Oh, you're right, my bad.

Just one little thing: why you remove tap from devDependencies and then add it into dependencies?

**Comment by cogluca** [comment]
sorry Mateo! Had a little local problem with tap and pnpm, uninstalled it and reinstalled it but forgot to add the --save-dev flag

**Comment by mateonunez** [comment]
@cogluca the pipeline fails. 😔

Try to remove the `pnpm-lock.yaml` file, we don't need to push it.

**Comment by cogluca** [comment]
made it run 🎉 I have honestly no idea what happened but it causes local issues when it is time to commit with the auto testing

**Comment by cogluca** [comment]
hey Mateo I removed the pnpm lock file but I think the CI pipeline needs it to set up the dependencies

**Comment by mateonunez** [comment]
@cogluca have you planned to change the committed files?

I suggest you to perform the following commands:

```bash
git reset docsUpdate~1
```

Then you should stage only the `README` file commit it and push it.

**Comment by cogluca** [comment]
@mateonunez sorry Mateo had some issues dealing with a detached head and retrieving the functioning hash, plus I have a little bug in the way with the current modules that I've fixed in an abrupt way

Long story short I tried the brute force approach, I'll fix that ASAP

Thanks for the suggestion

**Review by mateonunez — APPROVED** [review]
LGTM

**Pull request merged**
